apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dp016
    app.kubernetes.io/instance: dp016-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: dp016-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dp016-app
  template:
    metadata:
      labels:
        app: dp016-app
    spec:
      containers:
        - image: 325583868777.dkr.ecr.ca-central-1.amazonaws.com/dp016-repository:latest
          imagePullPolicy: Always
          name: dp016-app
          ports:
            - containerPort: 3000
